---
title: "Note"
author: "Gabriele Giuseppe Antonio Satta"
date: "2023-12-21"
output: html_document
---

# codice per fare il commit

questo documento contiene il codice da inserire nel teminal nper fare il commitsu git hub dinturti i file presemti nelle cartelle della directory del progetto

```{r}
git add -A && git commit -m 'messaggio di commit'
```

questo serve ler fare il pusch degli elemnenti
```{r}
git push origin master
```


questo serve per fare il pull
```{r}
git pull
```



# Cocice per commit e push di file di grandi dimensioni con il cmd
```{r}
PS C:\Users\satta> cd "G:\Altri computer\Il_mio_computer\DOTTORATO\PROGETTI\OLIVASTRO_PAULILATINO\Immagini_Planet\MERGE"

PS G:\Altri computer\Il_mio_computer\DOTTORATO\PROGETTI\OLIVASTRO_PAULILATINO\Immagini_Planet\MERGE> git init

PS G:\Altri computer\Il_mio_computer\DOTTORATO\PROGETTI\OLIVASTRO_PAULILATINO\Immagini_Planet\MERGE> git lfs install

PS G:\Altri computer\Il_mio_computer\DOTTORATO\PROGETTI\OLIVASTRO_PAULILATINO\Immagini_Planet\MERGE> git lfs track '*.tif'

PS G:\Altri computer\Il_mio_computer\DOTTORATO\PROGETTI\OLIVASTRO_PAULILATINO\Immagini_Planet\MERGE> git add .

PS G:\Altri computer\Il_mio_computer\DOTTORATO\PROGETTI\OLIVASTRO_PAULILATINO\Immagini_Planet\MERGE> git commit -m "Add tif files"


PS G:\Altri computer\Il_mio_computer\DOTTORATO\PROGETTI\OLIVASTRO_PAULILATINO\Immagini_Planet\MERGE> git remote add origin https://github.com/gsatta/Experimental_plots_VI.git

PS G:\Altri computer\Il_mio_computer\DOTTORATO\PROGETTI\OLIVASTRO_PAULILATINO\Immagini_Planet\MERGE> git push origin main
```

